vich_uploader:
    db_driver: orm

    mappings:
        workout_image:
            uri_prefix: /images/workouts
            upload_destination: '%kernel.project_dir%/public/images/workouts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
